[versions]
kotlin = "1.6.10"
gradleAndroid = "7.1.2"
material = "1.6.1"
jetpackCompose = "1.1.1"
jetpackComposeCompiler = "1.1.0-rc02"
jetpackComposeMaterial3 = "1.0.0-alpha07"
jetpackComposeNavigation = "2.4.1"
activityCompose = "1.4.0"
junit = "4.13.2"
assertJ = "3.22.0"
testAndroidCore = "1.4.0"
gradleVersionsPlugin = "0.42.0"

[libraries]
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "gradleAndroid" }
material = { module = "com.google.android.material:material", version.ref = "material" }
jetpackCompose-material3 = { module = "androidx.compose.material3:material3", version.ref = "jetpackComposeMaterial3" }
jetpackCompose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "jetpackComposeNavigation" }
jetpackCompose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "jetpackCompose" }
jetpackCompose-uiTooling-preview = { module = "androidx.compose.ui:ui-tooling", version.ref = "jetpackCompose" }
jetpackCompose-uiTest-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "jetpackCompose" }
jetpackCompose-uiTest-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "jetpackCompose" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
test-junit = { module = "junit:junit", version.ref = "junit" }
test-assertJ = { module = "org.assertj:assertj-core", version.ref = "assertJ" }
test-androidCore = { module = "androidx.test:core", version.ref = "testAndroidCore" }

[plugins]
gradleVersionsPlugin = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsPlugin" }